config/routes.rb
Crowdfunder::Application.routes.draw do

  resources :projects do
    resources :breakpoints, on: :collection
    resources :comments
  end
  resources :pledges, :except => [:index]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root 'projects#index'

  get 'tagged' => 'projects#tagged', :as => 'tagged'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :project

	# validates :user, presence: true
	# validates :project, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :load_project

	def new
		@comment = Comment.new
	end

	def index
		@comments = Comment.all
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def create
		@comment = @project.comments.build(comment_params)
		@comment.user = current_user

			if @comment.save
				redirect_to project_comments_path(@project)
			else
				render :new
			end
	end

	def edit
	    @comment = Comment.find(params[:id])
	end

	def update

	  @comment = Comment.find(params[:id])

	  if @comment.update_attributes(comment_params)
	  	redirect_to project_comments_path(@project)
	  else
	    render :edit
	  end
	end


	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to project_comments_path(@project)
	end

private

	def load_project
		@project = Project.find(params[:project_id])
	end

	def comment_params
	params.require(:comment).permit(:title, :project_id, :description)
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for [ @project, @comment ] do |f| %>
  <%= render partial: "shared/form_errors", locals: {anyword: @comment} %>
<p class="form-label">
	<%= f.label :title %></br>
	<%= f.text_field :title, size: 60 %>
</p>

<p class="form-label">
	<%= f.label :description %></br>
	<%= f.text_area :description, rows:20, cols:60 %>
</p>

<p class="form-label">
	<%= f.submit "Save", class: "button" %>
</p>

<% end %>

app/views/comments/edit.html.erb
  <div id="main">
    <div class="frame">
      <div class="col1 main-content" >
        <h1>Edit your comment</h1>

        <%= render "comment_form" %>

      </div>
    </div>
  </div>

app/views/comments/index.html.erb
<div id="main">
  <div class="frame">
    <div class="col1 main-content" >

			<h1>Project Comments</h1>

			<% if @project.comments.length > 0 %>
				<% @project.comments.each do |c| %>
				<div class="review">
					<h4><%= c.title.titleize %></h4>
				  <p><%= c.description %></p>
				  <em class="byline">Added on <%= c.created_at.localtime.strftime "%-d %B %Y" %> by <%= c.user.name %></em>
				      <% if current_user && (c.user == current_user) %>
				    		<span class="navigation-links">
				    		<%= link_to "Edit", edit_project_comment_path(@project, c) %> | <%= link_to "Delete", project_comment_path(@project, c), :confirm => "Are you sure you want to delete this?", :method => :delete %>
				    		</span>
				      <% end %>
				   </div>
				   <% end %>
			<% else %>
				<div class="review">No one commented on this project yet</div>
			<% end %>
		</div>
		<div class="col1 main-content" >
			<% if current_user %>
				<%= link_to "Add a comment", new_project_comment_path(@project) %>
			<% else %>
				Please <%= link_to "log in", new_session_path %> or <%= link_to "register", new_user_path %> to add a comment
			<% end %>

      </div>
    </div>
  <div class="frame">
  <%= link_to_function "Back", "history.back()"  %>
  </div>
  </div>

app/views/comments/new.html.erb
<h1> Project Comments</h1>

<% if current_user %>

	<%= form_for [ @project, @comment ] do |f| %>
	<p class="form-label">
		<%= f.label :title %></br>
		<%= f.text_field :title %>
	</p>

	<p class="form-label">
		<%= f.label :description %></br>
		<%= f.text_area :description %>
	</p>

	<p class="form-label">
		<%= f.submit "Save", class: "button" %>
	</p>

	<% end %>

	<% else %>
	<br>
	<br>
		<p> "Must login first" </p>
	<% end  %>