config/routes.rb
Crowdfunder::Application.routes.draw do

  resources :projects do
    resources :breakpoints, on: :collection
    resources :comments
  end
  resources :pledges, :except => [:index]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root 'projects#index'

  get 'tagged' => 'projects#tagged', :as => 'tagged'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, uniqueness: {case_sensitive: false, message: "already exists in our system"}
	has_many :projects, foreign_key: "owner_id"

	has_many :breakpoints, :through => :pledges
	has_many :pledges, foreign_key: "backer_id"

	has_many :comments, :through => :projects
	has_many :comments


	has_many :backed_projects, through: :pledges, source: "project"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    session[:return_to] = request.referrer
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to session[:return_to], :notice => "Registration successful!"
      session[:return_to] = nil
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :last_logged_in)
  end
end

app/helpers/users_helper.rb
module UsersHelper
def total_raised
	raised = 0
	current_user.breakpoints.each do |x|
		raised += x.amount_in_cents
	end
	raised
end

end

app/views/users/_user.html.erb
user.breakpoints.name

app/views/users/new.html.erb
  <div id="main">
    <div class="frame">
      <div class="col1 main-content" >
        <h1>Sign Up</h1>

        <%= form_for @user do |f| %>
        <%= render partial: "shared/form_errors", locals: {anyword: @user} %>

          <div class="form-label">
            <%= f.label :email %><br/>
            <%= f.text_field :email %>
          </div>
          <div class="form-label">
            <%= f.label :name %><br/>
            <%= f.text_field :name %>
          </div>
          <div class="form-label">
            <%= f.label :password %><br/>
            <%= f.password_field :password %>
          </div>
          <div class="form-label">
            <%= f.label :password_confirmation %><br/>
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="form-label">
          	<%= f.submit "Save", class: "button" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div id="main">
  <div class="frame">
    <div class="col1" >

			<% if current_user && (current_user.id == @user.id) %>
				<div class="main-content">
				<% if current_user.projects.length > 0  %>
					<h4>Here are your projects:</h4></br>
					<% current_user.projects.each do |p| %>
						<p>Project Name: <%= link_to p.name,project_path(p) %></p>
						<p>Project Goal: <%= display_money(p.goal_in_cents) %></p>
						<p>Total Raised: <%= display_money(total_pledges(p)) %></p>
						</br>
					<% end %>
				<% else %>
					You haven't started any projects. <%= link_to "Start a new project", new_project_path %>
				<% end %>
				</div>

				<div class="main-content">
				<% if current_user.pledges.length > 0 %>
					<h4>Here are the projects you backed: </h4>
						<% current_user.pledges.each do |bp|%>
							<p><%= link_to bp.project.name, project_path(bp.project.id)%> | <%= display_money(bp.breakpoint.amount_in_cents) %></p>
						<% end %></br>
					<h4>Total amount pledged:</h4>
					<%= display_money(total_raised) %>
				<% else  %>
					You haven't backed any projects yet. <%= link_to "Explore project", projects_path %>
				<% end %>
				</div>

			<% else %>
				<% if @user.projects.length > 0  %>
					<div class="main-content"><h4><%= @user.name.titleize %>'s projects:</h4></br>
					<% @user.projects.each do |p| %>
					<p>Project Name: <%= link_to p.name,project_path(p) %></p>
					<p>Project Goal: <%= display_money(p.goal_in_cents) %></p>
					<p>Total Raised: <%= display_money(total_pledges(p)) %></p>
					</br>
					<% end %></div>
				<% else %>
					<div class="main-content"><%= @user.name.titleize %> hasn't started any projects</div>
				<% end %>
			<% end %>
    </div>
  </div>
</div>