config/routes.rb
Crowdfunder::Application.routes.draw do

  resources :projects do
    resources :breakpoints, on: :collection
    resources :comments
  end
  resources :pledges, :except => [:index]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  root 'projects#index'

  get 'tagged' => 'projects#tagged', :as => 'tagged'

end

app/models/project.rb
class Project < ActiveRecord::Base
scope :newest_first, -> { order(created_at: :desc) }
belongs_to :owner, class_name: "User"
has_many :backers, :through => :pledges
has_many :breakpoints
has_many :pledges
has_many :comments


acts_as_taggable

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.newest_first
  end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user
    if @project.save
      redirect_to new_project_breakpoint_path(@project)
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def destroy
  end

  def show
    @project = Project.find(params[:id])
    if current_user
      @show_overlay = current_user.intro.nil?
      current_user.update_attribute(:intro, true)
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def tagged
    if params[:tag].present?
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.postall
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :user_id, :goal_in_cents, :start_date, :end_date, :description, :image, :tag_list)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	include ActsAsTaggableOn::TagsHelper

	def total_pledges(project)
		total_pledges = 0;
		project.breakpoints.each do |bp|
			total_pledges += (bp.pledges.size * bp.amount_in_cents)
		end
		total_pledges
	end

	def display_money(n_cents)
		number_to_currency(n_cents.to_f/100, precision: 0)
	end

	def display_money_short(n_cents)
		if n_cents < 10000000
			number_to_currency(n_cents.to_f/100, precision: 0)
		elsif n_cents < 100000000
			number_to_currency(n_cents.to_f/100000, precision: 0) + "K"
		else
			number_to_currency(n_cents.to_f/100000000, precision: 0) + "M"
		end
	end

	def backed_bp(user, project)
		if user.backed_projects.include?(project)
			return user.breakpoints.where(project: project)[0]
		else
			return false
		end
	end

	def time_to_close(project)
		distance_of_time_in_words(project.end_date - Time.now) if Time.now < project.end_date
	end
end

app/views/projects/_project.html.erb
<div class="col4">
	<div class="img-thumb-back">
	<%= link_to image_tag(project.image, class: "img-thumb"), project %>

	<table class="prod-overview">
		<tr>
			<th colspan="2">
			<%= link_to truncate(project.name, :length => 30, :separator => ' '), project  %>
			</th>
		</tr>
		<tr>
			<th colspan="2">
				<% if Time.now < project.end_date %>
					Ends in <%= time_to_close(project) %>
				<% else %>
					Ended <%= project.end_date.strftime "%Y-%m-%d" %>
				<% end %>
			</th>
		</tr>
		<tr>
			<td>Goal: <%= display_money_short(project.goal_in_cents) %></td>
			<td>Raised: <%= display_money_short(total_pledges(project))%></td>
		</tr>
	</table>
	</div>
</div>

app/views/projects/_project_form.html.erb
  <%= form_for @project do |f|%>
  <p class="form-label">
  	<%= f.label :name %></br>
  	<%= f.text_field :name %>
  </p>
  <p class="form-label">
		<%= f.label :goal_in_cents %></br>
		<%= f.number_field :goal_in_cents %>
	</p>
	<p class="form-label">
  	<%= f.label :start_date %></br>
  	<%= f.datetime_select:start_date %>
  </p>
  <p class="form-label">
  	<%= f.label :end_date %></br>
  	<%= f.datetime_select :end_date %>
  </p>
  <p class="form-label">
  	<%= f.label :description %></br>
  	<%= f.text_area :description %>
  </p>
  <p class="form-label">
  	<%= f.label :image %></br>
  	<%= f.text_field :image %>
  </p>
  <p class="form-label">
    <%= f.label :tags, "Tags (comma-separated)" %></br>
    <%= f.text_field :tag_list %>
  </p>
  <p class="form-label">
  	<%= f.submit label_text, class: "button" %>
  </p>
  <% end %>

app/views/projects/edit.html.erb
<div id="main">
  <div class="frame">
    <div class="col1 main-content" >
      <h1>Edit project details</h1>

      <%= render partial: "project_form", locals: {label_text: "Done"} %>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div id="main">
	<div id="projects" class="frame">
	<%= render @projects %>
	</div>
</div>

app/views/projects/new.html.erb
  <div id="main">
    <div class="frame">
      <div class="col1 main-content" >
        <h1>Start a project</h1>

        <%= render partial: "project_form", locals: {label_text: "Next"} %>

      </div>
    </div>
  </div>

app/views/projects/show.html.erb
<div id="main">
<div class="frame">
	<div class="col66">
	<div class="navigation-links"><%= link_to "Comments", project_comments_path(@project) %></div>
		<div class="img-back">
			<%= image_tag(@project.image, class: "img-full")  %>
		</div>
		<div class="prod-full">
			<h3 class="label-title"><%= @project[:name] %></h3>
			<h4 class="byline">by <%= link_to @project.owner.name, user_path(@project.owner) %></h4>
			<h4>Goal: <%= display_money(@project.goal_in_cents) %></h4>
			<p id="pledged" data-intro='This is how much has been raised by other backers' data-position='right'>Raised: <%= display_money(total_pledges(@project)) %></p>
			<p>Begins: <%= @project.start_date.localtime.strftime "%-d %B %Y at %I:%M%P"%></p>
			<p>Ends: <%= @project.end_date.localtime.strftime "%-d %B %Y at %I:%M%P" %></p>
				<div id="countdowntimer">
					<span id="future_date"></span>
				</div>
			<p data-intro='This is the product description' data-position='right'><%= @project[:description] %></p>
			<p class="main-content"><% @project.tags.any? %>
				Tags:
			  <% @project.tags.each do |tag| %>
			  <%= link_to tag.name, tagged_url(:tag => tag.name) %>
			  <% if tag != @project.tags.last %>
			  |
			  <% end  %>
			<% end %></p>
			  <% if @project.owner == current_user %>
					<span class="navigation-links">
					<%= link_to "Edit project details", edit_project_path(@project) %>
					</span>
			  <% end %>
		</div>
</div>


<div class="col3 breakpoints" data-intro='These are the different rewards you can pledge to. Remember that you cannot back out of a pledge once committed.' data-position='left'>
	<% @project.breakpoints.by_price.each do |bp| %>
		<div class="prod-full" id="tier-<%= bp.id %>" >
			<p class="label-title"><%= bp.title %></p>
			<h4 class="byline" id="pledges-<%= bp.id %>"><%= count_pledges(bp) %> backers
				<% if bp.limit > 0 %>
				&nbsp;&nbsp;&nbsp;<span class="limited">Limited: <%= bp.limit - count_pledges(bp) %> left of <%= bp.limit %></span>
				<% end %>
			</h4>
			<p><%= display_money(bp.amount_in_cents) %></p>
			<p><%= bp.description %></p>
			<p>
				<% if current_user %>
						<% if backed_bp(current_user, @project) %>
							<% if backed_bp(current_user, @project) == bp %>
								<h4 id="pledge_bp">&#8594;You pledged at this tier</h4>
							<% end %>
						<% elsif Time.now < @project.end_date %>
									<% if (@project.owner == current_user) %>
										<%= link_to "Edit tier", edit_project_breakpoint_path(@project, bp) %>
									<% elsif ((bp.limit == 0) || (bp.limit - count_pledges(bp) > 0)) %>
										<%= form_tag('/pledges', remote: true, class: "breakpoint") do %>
											<%= hidden_field_tag 'bp_id', bp.id %>
											<%= submit_tag "Pledge at this tier ", class: "button pledge_button" %>
										<% end %>
									<% end %>
					 	<% end %>
				 <% end %>
			</p>
		</div>
	<% end %>

	<div class="prod-full">
		<p>
			<% if time_to_close(@project) %>
				<% if @project.owner == current_user  %>
					<%= link_to "Add another tier", new_project_breakpoint_path(@project) %>
				<% elsif !current_user %>
					Please <%= link_to "log in", new_session_path %> or <%= link_to "register", new_user_path %> to back this project
				<% end %>
			<% else %>
				Funding closed on <%= @project.end_date.localtime.strftime "%Y-%m-%d" %>
			<% end %>
		</p>
	</div>
</div>
</div>
</div>
<script type="text/javascript">

	$("#future_date").countdowntimer({
      dateAndTime : "<%= "#{@project.end_date.localtime.strftime '%Y/%m/%d %T'}" %>",
      size : "sm",
      borderColor: "#FFFFFF",
      backgroundColor: "#AAAAAA",
      fontColor: "#FFFFFF"
	});

</script>
<% if current_user %>
	<% if @show_overlay %>
		<script>
			jQuery(document).ready(function($) {
				window.setTimeout(function(){
					$('body').chardinJs('start');
				}, 1000)
			});
		</script>
	<% end %>
<% end %>

app/views/projects/tagged.html.erb
<div id="main">
	<div id="projects" class="frame">
		<div class="col1 main-content" >
		<h2>Projects tagged "<%= params[:tag].upcase %>"</h2>
		<%= render @projects %>
		</div>
	</div>
	<div class="frame">
	<%= link_to_function "Back", "history.back()"  %>
	</div>
</div>